# Sniperkit-Bot
# - Status: analyzed

version: 2

jobs:
  build:
    docker:
      - image: golang:1.10
    working_directory: /go/src/github.com/sniperkit/snk.fork.pingcap-tidb
    steps:
      - checkout
      - run:
          name: "Build & Test"
          command: make dev
